query AccountByEmail {
  accountsByEmail(email: "intelphysic@gmail.com") {
    data {
      _id
      email
      userid
    }
  }
}

query AllUsers {
    query AllUsers {
        Accounts {
            data {
                userid
            }
        }
    }
}

query AccountsProjects {
  Accounts {
    data {
      _id
      userid
      email
      profile {
        _id
        projects {
          data {
            _id
            ProjectName
            Description
          }
        }
      }
    }
  }
}

query ProjectsByUserID {
  accountByUserID(userid: "rubrub"){
    data{
      _id
      email
      userid
      projects{
        data{
          _id
          ProjectName
          Description
        }
      }
    }
  }
}