type Account {
    email: String! @unique
    userid: String! @unique
    projects: [ Project ] @relation(name: "user")
}

type Project {
    Account: Account! @relation(name: "user")
    ProjectName: String!
    Tagline: String
    Description: String
    Download: String
    Source: String
    Docs: String
}

type Query {
    Accounts: [Account!]
    accountByEmail(email: String!): [Account!]
    accountByUserID(userid: String!): [Account!]
    Projects: [Project!]
}

